### ISSUE TITLE
PicoTutor - Strange Behavior

### ISSUE THREAD

**Issue by RandyR99** [JohanSjoblom/picochess#6]
Hi Johan,

I wanted to do a test of your async branch and also see if I could add the MAME files. MAME is working but PicoTutor seems to be acting strangely. I played the following moves (I'm White - the pgn file also needs fixing):

[Event "PicoChess game"]
[Site "Winnipeg, Canada CA"]
[Date "2025.02.04"]
[Round "?"]
[White "Boris (Level 01 - 1s move) (100%)"]
[Black "Player"]
[Result "*"]
[WhiteElo "985"]
[BlackElo "1500"]
[Time "10:19:42"]

1. e4 e6 2. d4 Bb4+ 3. c3 Bd6 4. Nf3 Nf6 5. Bd3

After I played Bd3 (I missed e5 which would win a piece) PicoTutos said it was a really bad move and that I should have played Be7 (which is perhaps what black should have played on its 3rd move). But my move of Bd3 is highlighted on the board (chesslink). So it appears that there is a mixup between whose turn it is and who is White. It should be noted that when using a retro engine, PicoTutor does not immediately pass a bad move to the retro engine allowing you to do a takeback (retro engines in PicoChess don't allow takebacks). The debug log is below.

Randy

```
2025-02-04 10:21:36.349   DEBUG  picochess - stop_search_and_clock: engine already waiting
2025-02-04 10:21:36.350   DEBUG  picochess - user_move: user did a move for user
2025-02-04 10:21:36.352   DEBUG  picotutor - log_pv_lists: PicoTutor White to move 5
2025-02-04 10:21:36.353   DEBUG  picotutor - log_pv_lists: 10 best:
2025-02-04 10:21:36.353   DEBUG  picotutor - log_pv_lists: e4e5 score 512 mate in 0 depth 8
2025-02-04 10:21:36.354   DEBUG  picotutor - log_pv_lists: d1c2 score 193 mate in 0 depth 8
2025-02-04 10:21:36.354   DEBUG  picotutor - log_pv_lists: f1d3 score 179 mate in 0 depth 8
2025-02-04 10:21:36.355   DEBUG  picotutor - log_pv_lists: b1d2 score 168 mate in 0 depth 8
2025-02-04 10:21:36.356   DEBUG  picotutor - log_pv_lists: d1e2 score 154 mate in 0 depth 8
2025-02-04 10:21:36.356   DEBUG  picotutor - log_pv_lists: f3g5 score 150 mate in 0 depth 8
2025-02-04 10:21:36.356   DEBUG  picotutor - log_pv_lists: d1d3 score 139 mate in 0 depth 8
2025-02-04 10:21:36.357   DEBUG  picotutor - log_pv_lists: c1g5 score 136 mate in 0 depth 8
2025-02-04 10:21:36.357   DEBUG  picotutor - log_pv_lists: f3d2 score 83 mate in 0 depth 8
2025-02-04 10:21:36.357   DEBUG  picotutor - log_pv_lists: f3e5 score 70 mate in 0 depth 8
2025-02-04 10:21:36.360   DEBUG  picotutor - log_pv_lists: 10 obvious:
2025-02-04 10:21:36.360   DEBUG  picotutor - log_pv_lists: e4e5 score 305 mate in 0 depth 1
2025-02-04 10:21:36.361   DEBUG  picotutor - log_pv_lists: f1d3 score 124 mate in 0 depth 1
2025-02-04 10:21:36.361   DEBUG  picotutor - log_pv_lists: b1d2 score 121 mate in 0 depth 1
2025-02-04 10:21:36.362   DEBUG  picotutor - log_pv_lists: d1c2 score 115 mate in 0 depth 1
2025-02-04 10:21:36.362   DEBUG  picotutor - log_pv_lists: d1e2 score 106 mate in 0 depth 1
2025-02-04 10:21:36.362   DEBUG  picotutor - log_pv_lists: c1g5 score 101 mate in 0 depth 1
2025-02-04 10:21:36.363   DEBUG  picotutor - log_pv_lists: f3d2 score 83 mate in 0 depth 1
2025-02-04 10:21:36.364   DEBUG  picotutor - log_pv_lists: d1d3 score 82 mate in 0 depth 1
2025-02-04 10:21:36.366   DEBUG  picotutor - log_pv_lists: f3g5 score 70 mate in 0 depth 1
2025-02-04 10:21:36.366   DEBUG  picotutor - log_pv_lists: d4d5 score 42 mate in 0 depth 1
2025-02-04 10:21:36.367   DEBUG     engine - stop: stop analyser
2025-02-04 10:21:36.686   DEBUG  picotutor - get_user_move_eval: lost centipawns 333 for move f1d3
2025-02-04 10:21:36.688   DEBUG  picotutor - get_user_move_eval: evaluation deep_low_diff = 55
2025-02-04 10:21:36.693   DEBUG  picotutor - get_user_move_eval: number of legal moves 37
2025-02-04 10:21:36.697   DEBUG  picotutor - get_user_move_eval: evaluation ??
2025-02-04 10:21:36.749   DEBUG    display - consume_message_queue: received message from msg_queue: MSG_PICOTUTOR_MSG
2025-02-04 10:21:36.788   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_DISPLAY_TEXT devs: i2c,ser,web
2025-02-04 10:21:36.788   DEBUG dispatcher - process_dispatch_message: (web) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:36.789   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:36.789   DEBUG dispatcher - _process_message: (web) showing DGT_DISPLAY_TEXT for 1.0 secs
2025-02-04 10:21:36.791   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:36.792   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:36.792   DEBUG dispatcher - _process_message: (ser) clock still not registered => ignore DGT_DISPLAY_TEXT
2025-02-04 10:21:36.805   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT started
2025-02-04 10:21:36.806   DEBUG     server - display_text_on_clock: [Pico Tutor: ??]
2025-02-04 10:21:36.806   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT ended
2025-02-04 10:21:37.789   DEBUG dispatcher - _stopped_maxtimer: (web) max timer finished - returning to time display
2025-02-04 10:21:37.809   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TIME started
2025-02-04 10:21:37.809   DEBUG     server - display_time_on_clock: (web) clock isnt running - no need for endText
2025-02-04 10:21:37.809   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TIME ended
2025-02-04 10:21:39.713   DEBUG    display - consume_message_queue: received message from msg_queue: MSG_PICOTUTOR_MSG
2025-02-04 10:21:39.760   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_DISPLAY_TEXT devs: i2c,ser,web
2025-02-04 10:21:39.761   DEBUG dispatcher - process_dispatch_message: (web) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:39.761   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:39.761   DEBUG dispatcher - _process_message: (web) showing DGT_DISPLAY_TEXT for 1.0 secs
2025-02-04 10:21:39.762   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:39.762   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:39.762   DEBUG dispatcher - _process_message: (ser) clock still not registered => ignore DGT_DISPLAY_TEXT
2025-02-04 10:21:39.766   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT started
2025-02-04 10:21:39.766   DEBUG     server - display_text_on_clock: [threat: Be7]
2025-02-04 10:21:39.767   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT ended
2025-02-04 10:21:40.090   DEBUG  transport - _log: EOF in transport thread
2025-02-04 10:21:40.762   DEBUG dispatcher - _stopped_maxtimer: (web) max timer finished - returning to time display
2025-02-04 10:21:40.769   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TIME started
2025-02-04 10:21:40.769   DEBUG     server - display_time_on_clock: (web) clock isnt running - no need for endText
2025-02-04 10:21:40.769   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TIME ended
2025-02-04 10:21:44.741   DEBUG    display - consume_message_queue: received message from msg_queue: MSG_PICOTUTOR_MSG
2025-02-04 10:21:44.789   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_DISPLAY_TEXT devs: i2c,ser,web
2025-02-04 10:21:44.790   DEBUG dispatcher - process_dispatch_message: (web) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:44.790   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:44.791   DEBUG dispatcher - _process_message: (web) showing DGT_DISPLAY_TEXT for 1.0 secs
2025-02-04 10:21:44.791   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:44.792   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:44.792   DEBUG dispatcher - _process_message: (ser) clock still not registered => ignore DGT_DISPLAY_TEXT
2025-02-04 10:21:44.839   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT started
2025-02-04 10:21:44.840   DEBUG     server - display_text_on_clock: [hint move: e5]
2025-02-04 10:21:44.840   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT ended
2025-02-04 10:21:45.791   DEBUG dispatcher - _stopped_maxtimer: (web) max timer finished - returning to time display
2025-02-04 10:21:45.794   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TIME started
2025-02-04 10:21:45.794   DEBUG     server - display_time_on_clock: (web) clock isnt running - no need for endText
2025-02-04 10:21:45.794   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TIME ended
2025-02-04 10:21:49.717   DEBUG  picochess - set_wait_state: new play mode: PlayMode.USER_BLACK
2025-02-04 10:21:49.719   DEBUG     engine - stop: stop analyser
2025-02-04 10:21:49.755   DEBUG picotalker - process_picotalker_messages: announcing PLAY_MODE
2025-02-04 10:21:49.771   DEBUG    display - consume_message_queue: received message from msg_queue: MSG_PLAY_MODE
2025-02-04 10:21:49.773   DEBUG    display - consume_message_queue: received message from msg_queue: MSG_CLOCK_STOP
2025-02-04 10:21:49.823   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_LIGHT_CLEAR devs: ser,web
2025-02-04 10:21:49.824   DEBUG dispatcher - process_dispatch_message: (web) max timer not running => processing command: DGT_LIGHT_CLEAR
2025-02-04 10:21:49.825   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR
2025-02-04 10:21:49.826   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_LIGHT_CLEAR
2025-02-04 10:21:49.826   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR
2025-02-04 10:21:49.827   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_DISPLAY_TEXT devs: web,i2c,ser
2025-02-04 10:21:49.829   DEBUG dispatcher - process_dispatch_message: (web) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:49.829   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:49.830   DEBUG dispatcher - _process_message: (web) showing DGT_DISPLAY_TEXT for 1.0 secs
2025-02-04 10:21:49.832   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:49.833   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:49.834   DEBUG dispatcher - _process_message: (ser) clock still not registered => ignore DGT_DISPLAY_TEXT
2025-02-04 10:21:49.835   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_CLOCK_STOP devs: i2c,ser,web
2025-02-04 10:21:49.836   DEBUG dispatcher - process_dispatch_message: (web) tasks delayed: [DGT_CLOCK_STOP]
2025-02-04 10:21:49.837   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_CLOCK_STOP
2025-02-04 10:21:49.838   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_CLOCK_STOP
2025-02-04 10:21:49.839   DEBUG dispatcher - _process_message: (ser) clock still not registered => ignore DGT_CLOCK_STOP
2025-02-04 10:21:49.873   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR started
2025-02-04 10:21:49.874   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR ended
2025-02-04 10:21:49.874   DEBUG      iface - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR started
2025-02-04 10:21:49.875   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT started
2025-02-04 10:21:49.875   DEBUG      board - clear_light_on_revelation: turn LEDs off
2025-02-04 10:21:49.875   DEBUG     server - display_text_on_clock: [Player Black]
2025-02-04 10:21:49.875   DEBUG      iface - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR ended
2025-02-04 10:21:49.876   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT ended
2025-02-04 10:21:49.910   DEBUG chess_link_bluepy - handleNotification: BLE: Handle: 55, data: b'\xf878'
2025-02-04 10:21:49.910   DEBUG chess_link_bluepy - handleNotification: BLE received [x78]
2025-02-04 10:21:49.910   DEBUG chess_link_bluepy - handleNotification: bluepy_ble received complete msg: x78
2025-02-04 10:21:49.917   DEBUG chess_link - _event_worker_thread: got led-off reply
2025-02-04 10:21:50.427   DEBUG  picochess - stop_search_and_clock: engine already waiting
2025-02-04 10:21:50.429   DEBUG  picochess - process_fen: fen: rnbqk2r/pppp1ppp/3bpn2/8/3PP3/2PB1N2/PP3PPP/RNBQK2R result: True
2025-02-04 10:21:50.439   DEBUG picotalker - process_picotalker_messages: announcing TAKE_BACK
2025-02-04 10:21:50.444   DEBUG    display - consume_message_queue: received message from msg_queue: MSG_TACK_BACK
2025-02-04 10:21:50.496   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_LIGHT_CLEAR devs: ser,web
2025-02-04 10:21:50.497   DEBUG dispatcher - process_dispatch_message: command doesnt change the clock display => (web) max timer ignored
2025-02-04 10:21:50.498   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR
2025-02-04 10:21:50.499   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_LIGHT_CLEAR
2025-02-04 10:21:50.501   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR
2025-02-04 10:21:50.503   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_DISPLAY_TEXT devs: i2c,ser,web
2025-02-04 10:21:50.506   DEBUG dispatcher - process_dispatch_message: (web) tasks delayed: [DGT_CLOCK_STOP, DGT_DISPLAY_TEXT]
2025-02-04 10:21:50.508   DEBUG      iface - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR started
2025-02-04 10:21:50.509   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_DISPLAY_TEXT
2025-02-04 10:21:50.518   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:50.519   DEBUG dispatcher - _process_message: (ser) clock still not registered => ignore DGT_DISPLAY_TEXT
2025-02-04 10:21:50.517   DEBUG      board - clear_light_on_revelation: turn LEDs off
2025-02-04 10:21:50.522   DEBUG      iface - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR ended
2025-02-04 10:21:50.521   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_DISPLAY_MOVE devs: i2c,ser,web
2025-02-04 10:21:50.526   DEBUG dispatcher - process_dispatch_message: (web) tasks delayed: [DGT_CLOCK_STOP, DGT_DISPLAY_TEXT, DGT_DISPLAY_MOVE]
2025-02-04 10:21:50.527   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_DISPLAY_MOVE
2025-02-04 10:21:50.529   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_DISPLAY_MOVE
2025-02-04 10:21:50.529   DEBUG dispatcher - _process_message: (ser) clock still not registered => ignore DGT_DISPLAY_MOVE
2025-02-04 10:21:50.536   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_LIGHT_CLEAR devs: ser,web
2025-02-04 10:21:50.539   DEBUG dispatcher - process_dispatch_message: command doesnt change the clock display => (web) max timer ignored
2025-02-04 10:21:50.540   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR started
2025-02-04 10:21:50.541   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR
2025-02-04 10:21:50.543   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR ended
2025-02-04 10:21:50.544   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_LIGHT_CLEAR
2025-02-04 10:21:50.546   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR
2025-02-04 10:21:50.547   DEBUG dispatcher - process_dispatch_queue: received command from dispatch_queue: DGT_LIGHT_SQUARES devs: ser,web
2025-02-04 10:21:50.548   DEBUG dispatcher - process_dispatch_message: command doesnt change the clock display => (web) max timer ignored
2025-02-04 10:21:50.549   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_LIGHT_SQUARES
2025-02-04 10:21:50.550   DEBUG dispatcher - process_dispatch_message: (ser) max timer not running => processing command: DGT_LIGHT_SQUARES
2025-02-04 10:21:50.551   DEBUG dispatcher - _process_message: (ser) handle DgtApi: DGT_LIGHT_SQUARES
2025-02-04 10:21:50.575   DEBUG      iface - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR started
2025-02-04 10:21:50.581   DEBUG      board - clear_light_on_revelation: turn LEDs off
2025-02-04 10:21:50.592   DEBUG      iface - _process_message: (ser) handle DgtApi: DGT_LIGHT_CLEAR ended
2025-02-04 10:21:50.592   DEBUG      iface - _process_message: (ser) handle DgtApi: DGT_LIGHT_SQUARES started
2025-02-04 10:21:50.593   DEBUG      board - light_squares_on_revelation: turn LEDs on - move: f1d3
2025-02-04 10:21:50.594   DEBUG      iface - _process_message: (ser) handle DgtApi: DGT_LIGHT_SQUARES ended
2025-02-04 10:21:50.605   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR started
2025-02-04 10:21:50.606   DEBUG chess_link_bluepy - handleNotification: BLE: Handle: 55, data: b'\xf878'
2025-02-04 10:21:50.620   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_LIGHT_CLEAR ended
2025-02-04 10:21:50.620   DEBUG chess_link_bluepy - handleNotification: BLE received [x78]
2025-02-04 10:21:50.622   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_LIGHT_SQUARES started
2025-02-04 10:21:50.639   DEBUG chess_link_bluepy - handleNotification: bluepy_ble received complete msg: x78
2025-02-04 10:21:50.662   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_LIGHT_SQUARES ended
2025-02-04 10:21:50.671   DEBUG chess_link - _event_worker_thread: got led-off reply
2025-02-04 10:21:50.772   DEBUG chess_link_bluepy - handleNotification: BLE: Handle: 55, data: b'\xf878'
2025-02-04 10:21:50.773   DEBUG chess_link_bluepy - handleNotification: BLE received [x78]
2025-02-04 10:21:50.773   DEBUG chess_link_bluepy - handleNotification: bluepy_ble received complete msg: x78
2025-02-04 10:21:50.776   DEBUG chess_link - _event_worker_thread: got led-off reply
2025-02-04 10:21:50.831   DEBUG dispatcher - _stopped_maxtimer: processing delayed (web) tasks: [DGT_CLOCK_STOP, DGT_DISPLAY_TEXT, DGT_DISPLAY_MOVE]
2025-02-04 10:21:50.831   DEBUG dispatcher - _stopped_maxtimer: (web) tasks has 3 members
2025-02-04 10:21:50.832   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_CLOCK_STOP
2025-02-04 10:21:50.832   DEBUG dispatcher - _stopped_maxtimer: (web) tasks has 2 members
2025-02-04 10:21:50.833   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT
2025-02-04 10:21:50.834   DEBUG dispatcher - _process_message: (web) showing DGT_DISPLAY_TEXT for 1.0 secs
2025-02-04 10:21:50.835   DEBUG dispatcher - _stopped_maxtimer: (web) tasks stopped on 1 remaining members
2025-02-04 10:21:50.867   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_CLOCK_STOP started
2025-02-04 10:21:50.868   DEBUG      iface - _process_message: (web) clock is already stopped
2025-02-04 10:21:50.868   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_CLOCK_STOP ended
2025-02-04 10:21:50.868   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT started
2025-02-04 10:21:50.869   DEBUG     server - display_text_on_clock: [takeback   ]
2025-02-04 10:21:50.870   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TEXT ended
2025-02-04 10:21:51.353   DEBUG chess_link_bluepy - handleNotification: BLE: Handle: 55, data: b'\xec\xb6C'
2025-02-04 10:21:51.354   DEBUG chess_link_bluepy - handleNotification: BLE received [l6C]
2025-02-04 10:21:51.354   DEBUG chess_link_bluepy - handleNotification: bluepy_ble received complete msg: l6C
2025-02-04 10:21:51.362   DEBUG chess_link - _event_worker_thread: got led-set reply
2025-02-04 10:21:51.834   DEBUG dispatcher - _stopped_maxtimer: processing delayed (web) tasks: [DGT_DISPLAY_MOVE]
2025-02-04 10:21:51.835   DEBUG dispatcher - _stopped_maxtimer: (web) tasks has 1 members
2025-02-04 10:21:51.841   DEBUG dispatcher - _process_message: (web) handle DgtApi: DGT_DISPLAY_MOVE
2025-02-04 10:21:51.862   DEBUG dispatcher - _process_message: (web) showing DGT_DISPLAY_MOVE for 1.0 secs
2025-02-04 10:21:51.864   DEBUG dispatcher - _stopped_maxtimer: (web) tasks completed
2025-02-04 10:21:51.911   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_MOVE started
2025-02-04 10:21:51.912   DEBUG     server - display_move_on_clock: [ 5.f1d3]
2025-02-04 10:21:51.914   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_MOVE ended
2025-02-04 10:21:52.865   DEBUG dispatcher - _stopped_maxtimer: (web) max timer finished - returning to time display
2025-02-04 10:21:52.899   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TIME started
2025-02-04 10:21:52.899   DEBUG     server - display_time_on_clock: (web) clock isnt running - no need for endText
2025-02-04 10:21:52.900   DEBUG      iface - _process_message: (web) handle DgtApi: DGT_DISPLAY_TIME ended

```

**Comment by RandyR99** [comment]
I continued the game but received an error "ERROR  picochess - think: fatal error no move received from engine". I don't think it's related in any way and may be a MAME issue. But the pgn file was different.

[Event "PicoChess game"]
[Site "Winnipeg, Canada CA"]
[Date "2025.02.04"]
[Round "?"]
[White "Player"]
[Black "Boris (Level 01 - 1s move) (100%)"]
[Result "*"]
[WhiteElo "1500"]
[BlackElo "985"]
[Time "10:19:42"]

1. e4 e6 2. d4 Bb4+ 3. c3 Bd6 4. Nf3 Nf6 5. Bd3 O-O 6. e5 Bxe5 7. dxe5 Ng4 8. h3 Nxf2 9. Kxf2 d6 10. Re1 dxe5 11. Nxe5 Qh4+ 12. Kg1 Na6 13. Re4 Qg3 14. Bf4 Qh4 15. Nf3 Qh5 16. Re5

**Comment by RandyR99** [comment]
I tested using PicoChess 3.2 (which has the same MAME installation as I used above) and the Boris retro engine did not give the 'no move' error. PicoTutor worked as expected (calling out my missed forced mate at move 15 below).

[Event "PicoChess game"]
[Site "Winnipeg, Canada CA"]
[Date "2025.02.04"]
[Round "?"]
[White "Randy"]
[Black "Boris (rev. 01) (pos) (Level 01 - 1s move) (100%)"]
[Result "1-0"]
[BlackElo "985"]
[Time "14:20:41"]
[WhiteElo "948"]

1. e4 e5 2. d4 exd4 3. Nf3 c5 4. Bc4 a6 5. Bf4 Qa5+ 6. Nbd2 d6 7. O-O Be6 8. Bd5 Bxd5 9. exd5 Nf6 10. Re1+ Kd8 11. Bg5 b5 12. Ne4 Nd7 13. Qe2 Qb4 14. Nxf6 Nxf6 15. Bxf6+ gxf6 16. Qe8+ Kc7 17. Qc6+ Kb8 18. Re8+ Ka7 19. Qc7#

**Comment by tosca07** [comment]
Don’t know if you have changed the behavior on purpose, but the picotutor in case of a blunder no longer points out the opponent move, but only the move suggestion instead

**Comment by tosca07** [comment]
This is really strange<: The missing announcement of the threat move is not deterministic - from time to time the threat move is correctly shown and announced in case of a blunder but sometoimes it is missing - hm!?

**Comment by tosca07** [comment]
Besides the inconsistent behavior by announcing the threat move in case of a blunder it also look like the calculation rules for blunder, bad, and good and "interesting" moves have changed (some drastically): Even if I blunder my queen I don't get a blunder warning only a bad move hint.

**Comment by JohanSjoblom** [comment]
I have not changed any picotutor behaviour "by purpose". I have tried to preserve the functionality of both main picochess.py and picotutor to keep it as "original as possible". My goal is that in the first release it should be a one-to-one replacement and work with all existing image engines. Once it works as the existing one then improvements can be discussed, but I think we need to get to a stable "replacement state" as the first goal.

The change of libraries and the async change might have caused some bugs that need more testing to make sure it behaves like the existing one. Now that I have fixed some other stabilizing things I think I need to retest the picotutor functionality...

One specific thing I will test is the take-back... I think currently it leads to a "pause" of 2 moves after take-back before the picochess starts to give evaluations. So I need to test at least that one.

**Comment by JohanSjoblom** [comment]
I have tested some more now... and I can synchronize a user takeback with picotutor so that it does not lose its history. Like an auto-takeback when you blunder against a mame engine.

But if the engine has also played its move and you do first a takeback on the engine move... at this point picochess sends a new color to picotutor (like a color change) which leads to loss of history and the tutor has to start from scratch. When you then also take back your own user move as a second step the history had already been emptied by the takeback of the engine move.

I guess we can live with this... it means that in these kind of takebacks you dont get any score for your first "new move"...

I have to make a few fixes in order to have synchronisation between picochess and picotutor. I think I found where the error was for the "strange behaviour"... Root cause: The picochess never sent a push move for the new user move because state.takeback_active was still true while handling the user move (it becomes False only at the end).... Sequence: First computer move takeback, then your move takeback, then user move repeat (new move or same) --> user move is not pushed to picotutor.

So I know now how to make a fix... But it will not be able to keep the history when you takeback computer moves... unless there is a way for the user to ask for takeback of both computer move and user move in one "go"...

I will be back with a fix...

**Comment by JohanSjoblom** [comment]
I have a branch now that works much better... will still test it for a while before committing it. Now picotutor only needs one history move and it does not lose history when doing takeback.

To test this branch do> git checkout 2025-03-pitotutor-check

**Comment by JohanSjoblom** [comment]
Now the colour and the takeback stays in sync in picotutor.

To solve the problem if you make a really bad move, like blunder your queen, I raised the VALID_ROOT_MOVES in picotutor from 10 to 30. If you have capacity, like on a Pi5, it could be perhaps higher. The challenge is that if you make a move that is not one of the 30 best moves (earlier 10) AND that the score difference between move 1 and move 30 is lower than very bad move (150) it will not evaluate it to ??. Currently if you miss all the 30 best moves it evaluates it to the same value as the diff between move 1 and 30.

Now with 30 lines analysed instead of 10 its less likely that you can blunder a queen and only get one ?. Its still possible in some cases of course. The only way to be sure would be to raise the VALID_ROOT_MOVES even higher... and/or to lover the very bad move (VERY_BAD_MOVE_TH) values in picotutor_constants.py. We have to experiment and find out what is the best practical value.

I am closing this issue now as I merged the solution into the main branch. Lets open new issues if there are still strange behaviours with the picotutor.

**Comment by tosca07** [comment]
Thanks for all the Tutor fixes, Johan!  Still I don't know if evaluation/classification ?/??/!/!? etc. is still the same (e.g. a good or very good move is not only a move which obviously has a evalutration advantage after the next moves but only when it is not only obviously a good move in the short time but in  the longtime (at least !!) (but we don't have to keep these old calculation rules).
But there is still bug : Although I have set the Coach to option "lift" the coach is not activated when I lift my own king - wait for the stop pieces message- and put the king back (that should invoke the Coach. But this does not wirk....

**Comment by JohanSjoblom** [comment]
Yes, I actually noticed myself that lift does not work... I need to debug
it...

Den sön 23 mars 2025 20:48tosca07 ***@***.***> skrev:

**Comment by JohanSjoblom** [comment]
And the formula should still be the same, it was just optimised to allow a
smaller number of obvious moves (now 10). If we increase also the
picotutor_constant for the obvious low root moves we should get exactly the
same formula result.

Den sön 23 mars 2025 21:02Johan Sjöblom ***@***.***> skrev:

**Comment by JohanSjoblom** [comment]
Ok, some improvements to picotutor
1) raised constant for obviousmoves from 10 to 50 which brings it closer to original as we get more accurate low-to-high
2) matescore was hardcoded to 999, raised it to 99.999 as the new chess library uses centipawns
I played a mate move and got a bad move verdict ?? because non-mating moves had almost 5000 cp due to my material advantage…. the mating score was only 998 (999 minus mate in one)

To be able to determine as close behaviour as the old picotutor I will collect the old and new constant values to a table for overview so that we together can check what values we want in centipawns. I can also put the formulas in there. They should be the same as long as we make one of the top 50 moves. I will send the table in the google group for everyone to comment.
Maybe we find some more actions from that table.

Or maybe now with the changes 1,2 it already is vey close to existing/old tutor…

**Comment by JohanSjoblom** [comment]
Here were the picotutor scores before my mate move Nd4-f5 which got a ?? verdict :-)
2025-03-30 12:30:24.972   DEBUG  picotutor - log_pv_lists: 50 best:
2025-03-30 12:30:24.973   DEBUG  picotutor - log_pv_lists: d4f5 score 998 mate in 1 depth 15
2025-03-30 12:30:24.973   DEBUG  picotutor - log_pv_lists: f8g8 score 993 mate in 6 depth 17
2025-03-30 12:30:24.974   DEBUG  picotutor - log_pv_lists: c3d5 score 992 mate in 7 depth 17
2025-03-30 12:30:24.974   DEBUG  picotutor - log_pv_lists: d3g6 score 992 mate in 7 depth 17
2025-03-30 12:30:24.974   DEBUG  picotutor - log_pv_lists: d4c6 score 989 mate in 10 depth 17
2025-03-30 12:30:24.974   DEBUG  picotutor - log_pv_lists: e7f6 score 988 mate in 11 depth 17
2025-03-30 12:30:24.975   DEBUG  picotutor - log_pv_lists: f8f2 score 986 mate in 13 depth 17
2025-03-30 12:30:24.975   DEBUG  picotutor - log_pv_lists: c3e4 score 986 mate in 13 depth 17
2025-03-30 12:30:24.975   DEBUG  picotutor - log_pv_lists: d3e4 score 983 mate in 16 depth 17
2025-03-30 12:30:24.976   DEBUG  picotutor - log_pv_lists: h2h3 score 4645 mate in 0 depth 17
2025-03-30 12:30:24.977   DEBUG  picotutor - log_pv_lists: h2h4 score 4640 mate in 0 depth 17
2025-03-30 12:30:24.977   DEBUG  picotutor - log_pv_lists: a1g1 score 3551 mate in 0 depth 17
2025-03-30 12:30:24.977   DEBUG  picotutor - log_pv_lists: d4e6 score 3477 mate in 0 depth 17
2025-03-30 12:30:24.978   DEBUG  picotutor - log_pv_lists: h5g6 score 1823 mate in 0 depth 17
2025-03-30 12:30:24.978   DEBUG  picotutor - log_pv_lists: e7g5 score 1778 mate in 0 depth 17
2025-03-30 12:30:24.979   DEBUG  picotutor - log_pv_lists: f8f3 score 1673 mate in 0 depth 17

and the game was like this me playing white against Stockfish 2100 setting... It made quite a blunder for 2100.
1. e4 c5 2. Nf3 e6 3. d4 cxd4 4. Nxd4 a6 5. Nc3 Qc7 6. Bd3 Nc6 7. Be3 b5 8. O-O
Bb7 9. Kh1 Ne5 10. Qe2 Be7 11. f4 Ng6 12. a3 Rc8 13. f5 Nh4 14. fxe6 Nf6 15.
exf7+ Kxf7 16. Qh5+ g6 17. Qxh4 h5 18. Bg5 Rcg8 19. Bxf6 Qb6 20. Bxe7+ Kg7 21.
e5 Rh6 22. Rf2 g5 23. Qxg5+ Kh8 24. Rf8 Rg6 25. Qxh5+ Kg7 26. Nf5# 1-0
So this last Nf5 was given a ?? verdict even though it was a mating move :-)

**Comment by tosca07** [comment]
Sounds good, Johan. Once we have similar PicoTuor behavior we are free to improve and fine tune the  settings and range tables. The most difficult part is always the !! if I remember correct because these are most which are not obviously classified as a good move (meaning not so good evaluation with shallow depth) but having a very good evaluation with a deeper depth). At least this was one concept for determining the !, !!  comments I got with the formulas I found in the web.

**Comment by JohanSjoblom** [comment]
Exactly. First find a state where old picotutor (and picochess main) behaviour is reproduced… and when that is stable then we can think about improvements or changes.
The Cambridge idea is quite clever indeed, a !! move shall not be obvious. And the low-high diff compares the scores low/shallow to high/deep. Now that we have 50 best moves configured for both shallow and deep the diff should be more accurate and therefore it should now be closer to the original.

**Comment by tosca07** [comment]
I still think there's is something strange with the current settings at least in comparison to the old tutor evaluation for a blunder ??  move: If I sacrify my bishop (like by playing white with 1. e4 e5 2. Ba6) I inly get a ? not a ?? but this move is obviously a blunder with ??.  Is this only a question of parameter values fro the tutor?

**Comment by JohanSjoblom** [comment]
Have to check. Do you have the log file? I have some restrictions on the
first move... but this was move 2....

Den fre 4 apr. 2025 20:06tosca07 ***@***.***> skrev:

**Comment by tosca07** [comment]
No log file, sorry ( I still have not my full development system available). I just ran the install-picochess.sh fiel again and just played these two moves against stockfish (so it should be easy to reproduce...)

**Comment by JohanSjoblom** [comment]
I could not yet repeat the problem with e4, e5 (or c5) 2. Ba6… i get a ?? every time… But I need to test more…

**Comment by tosca07** [comment]
With the latest update(s)= it seems to work now, Johan.
