### ISSUE TITLE
Farewell message not cleared from DGTPi display after shutdown

### ISSUE THREAD

**Issue by djdekker** [JohanSjoblom/picochess#73]
When shutting down the DGTPi with both White queens on d1 & e1, the DGTPi displays its farewell message as expected. However, once the DGTPi has shut down, the farewell message remains on the display. I think the display should go blank, as it used to do in the past.

**Comment by JohanSjoblom** [comment]
Oh, right. i did not know about this function :-)
I wonder if there is some list somewhere on how to send various signals using the queen (or other pieces)I know about the mode setting, queen a5,…f5.

Anyway, I need to check that it properly shuts down on this signal. It probably now only calls the old shutdown function without propely cleaningbup first. And if it properly shuts down, its hould clear the text display then I guess.

My dgtpi usually end up with the checkmate text on it :-)

**Comment by RandyR99** [comment]
I guess I should hace commented over here instead of https://github.com/JohanSjoblom/picochess/issues/76

**Comment by RandyR99** [comment]
Also see new issue #79.

**Comment by djdekker** [comment]
There is a RPi 3B+ inside my DGTPi. Following the instructions in issue #79 I applied these changes to /boot/firmware/config.txt:
```
core_freq=250
core_freq_min=250
```

Unfortunately, this did not solve the issue.

I'm still trying to find a 100% certain way to reproduce the issue. Sometimes the farewell message is cleared, sometimes it is not.

**Comment by JohanSjoblom** [comment]
It might be a rights issue. There is a shell script to install the dgtpi named install-dgtpi-clock.sh

I wonder if it would help to run this line from it using sudo?

setcap 'cap_net_bind_service,cap_sys_rawio,cap_dac_override+eip' /usr/bin/python3.11

**Comment by JohanSjoblom** [comment]
Interesting. Shutting down with 2 queens actually clears the DGTPI display.... And it that case the dgtpicom logs a return value of zero... If you ask it from the menu it fails with -3. 

Quite strange. Especially since this is the exact same code as in Pico 3.

The only difference is when asking for shutdown from the menu it runs:
self.dgtmenu.set_engine_restart(True)
... Later I will check if removing this row would fix it...

**Comment by RandyR99** [comment]
I had the impression that PicoChess was getting shut down before the clear display command was set, but maybe not. I have also seen it where the display would be cleared but then a 'lost communication' message would be displayed when using chess link (Millennium board), as if that process was still running. I guess we could always add a 'sudo /opt/picochess/etc/dgtpicom' as an ExecStop for picochess.service to clear the display.

**Comment by JohanSjoblom** [comment]
AH, its a random event. Now I got text left on screen when shutting down using 2 white queens…

This suggests its a race or timing issue with perhaps the eboard board communication interfering… an extra sleep time before the call could actually help… Or closing the eboard board communication before clearing the screen. Some other process is using the dgtpicom at the same time causing the -3 return.

It can also be as you say that shutdown stops it from happening, I had added a 0.2 sleep, but tomorrow I could test with 1 sec before and after… I do however suspect its the board communication.

**Comment by JohanSjoblom** [comment]
I think I nailed this one. If the (existing pico logic) fails to clear the screen it now re-initialises the dgtpicom library and calls again. I got this idea from the pico boot sequence... After a failed clear the next boot sequency will notice it and reset the clock, so I simply use the same clock reset.

Lets see if it now always clears the dgtpi screen. Otherwise the correct and more clean method would be to stop the eboard communication before calling shutdown in utilities.

**Comment by djdekker** [comment]
Hi Johan,

Thank you very much for all the effort you're putting into this issue. I have updated the code to the latest version with sudo git pull and reinstalled the DGTPi with the updated install script.

Unfortunately, shutdown behaviour of my DGTPi is still inconsistent.

Sometimes the farewell message is cleared, sometimes it isn't. In the latter case, I do see the monitor icon disappearing, proving that the clock and the RPi inside are no longer connected, but the message is not cleared from the display until I press the on/off button on the bottom of the DGTPi.

In the video you can see this at 0:00:07.20
https://github.com/user-attachments/assets/f93098f5-aa1c-4f39-82a3-f4c343e0ba53

**Comment by djdekker** [comment]
Hi Johan,

This commit solves the issue. The DGTPi powers down correctly with a blank display. Thank you very much!

**Comment by JohanSjoblom** [comment]
Nice, finally nailed it then. I also added the same logic to the menu choice "exit picochess" as tosca07 mentioned...
One open question though, maybe @tosca07 can answer it:

I noticed that the existing code was trying to do "sudo systemctl stop dgtpi" to stop the dgtpi service if you ask for "exit picochess" from the menu. There was a small typo there, so the existing code had "sudo systemctrl stop dgpi" - notice the missing letter "t". This means that the dgtpi service has currently not been stopped. I corrected the spelling mistake so it means that now "exit picochess" will close the dgtpi service.
See last change on the latest commit (scroll to the bottom): https://github.com/JohanSjoblom/picochess/commit/d361a5699a3936871d9f9480e7f6a2bd39ff3dae
Did I make a mistake by correcting that typo?

The open Question: Is this what we want? What is the purpose of "exit picochess" on a DGTPI clock? Do we want to close the dgtpi service?

**Comment by tosca07** [comment]
I guess normally people using a simple stock DGTPI wont use the exit function at all so i think your change is ok and nobody will get aware of this change.

The exit function was intended for people using the pi as a normal desktop computer and want to do other stuff after having played with picochess eg. playing with their eboards and the web browser on chess.com or lichess .org (which I Do) - so not the typical DGTPI use case.

**Comment by JohanSjoblom** [comment]
Thanks and OK. Yes I also find it useful with the "Exit Picochess" on DGTPI clock when I debug and test. No need to keep restarting the DGT... I can just start and stop the picochess and dgtpi services as I need respectively...

I will still have a look if I can further prevent some unnecessary messaging after shutdown/reboot or exit has been asked for. At least I think I need to stop the background analyser that is used in hint/eval/analysis mode... And I will have a look on how to close eboard communication.

**Comment by RandyR99** [comment]
I don't think it's necessary to stop the dgtpi.service as it's a oneshot.

Randy
